#!/bin/bash 
ls -la /d/Programming/alx-system-engineering-devops/0x00-shell_basics[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[_[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C /d/Programming/alx-system_engineering-devops /d/Programming
